# Variables
$inFocusOpacity = 0.92
$notInFocusOpacity = 0.92#0.85

$inFocusOpacityCode = 0.93
$notInFocusOpacityCode = 0.93#0.85

windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Default opacity for all windows
windowrule = no_blur on, opacity 1 1, match:class .*

# Firefox dev-ed fully opaque
windowrule = opacity 1 1, match:class ^(firefox-developer-edition)$

# Kitty custom opacity
windowrule = opacity 1 1, match:class ^(kitty)$
windowrule = float on, opacity 1 1, size 1000 745, match:class ^(kitty_small)$

# Browsers
#windowrule = opacity $inFocusOpacity $notInFocusOpacity, match:class ^(brave|chromium|librewolf|qutebrowser|zen-browser)$

# Spotify / Discord / Telegram / VS Code / Thunar or Nemo by title
windowrule = no_blur on, opacity $inFocusOpacity $notInFocusOpacity, match:title .*Spotify.*
windowrule = no_blur on, opacity $inFocusOpacity $notInFocusOpacity, match:title .*Discord.
windowrule = no_blur on, opacity $inFocusOpacity $notInFocusOpacity, match:title .*Telegram.*
windowrule = no_blur on, opacity $inFocusOpacityCode $notInFocusOpacityCode, match:title .*Visual Studio Code.*
# windowrule = no_blur on, opacity $inFocusOpacity $notInFocusOpacity, match:title .*(Thunar|nemo).*

